### ISSUE TITLE
Very slow with whole TIGER data

### ISSUE THREAD

**Issue by igorshubovych** [geocommons/geocoder#7]
I imported whole TIGER data array.
All requests are extremely slow.

**Comment by wonderchook** [comment]
Are you sure you built the indexes?

**Comment by igorshubovych** [comment]
yes. there are indexes. and it is still slow

**Comment by wonderchook** [comment]
How big is the database (should be about 4 gigs)?  And could you define slow?  How long is a single request taking?  Are you using the same Sinatra apps or running a script?  What sort of system are you using?

**Comment by igorshubovych** [comment]
Very interesting.
I checked again and it works quite fast. There were no changes to database.

**Comment by igorshubovych** [comment]
thank you anymore

**Comment by wonderchook** [comment]
Closed since it appears to be working.
