### ISSUE TITLE
no such file to load -- geocoder/us/import/tiger (LoadError)

### ISSUE THREAD

**Issue by issackelly** [geocommons/geocoder#8]
This is the error message that I'm getting

```
 ~/geocoder# bin/tiger_import
    bin/tiger_import:3:in `require': no such file to load -- geocoder/us/import/tiger (LoadError)
from bin/tiger_import:3
```

I ran `make install` so the gem should be available system-wide.
If I add the full path to tiger_import:3 it works, but the default install as suggested by Readme.txt isn't working for me.

**Comment by wonderchook** [comment]
This should be resolved now.  Was due to a typo in import.rb
