### ISSUE TITLE
Problem with tiger_import (possible typo)

### ISSUE THREAD

**Issue by jgarratt** [geocommons/geocoder#9]
Hi.  Thanks for providing this package.

When trying to import the tiger shapefiles I was getting this error:
./lib/geocoder/us/import.rb:157:in `join': can't convert false into String (TypeError)
    from ./lib/geocoder/us/import.rb:157:in`import_tree'
    from bin/tiger_import:9
    from bin/tiger_import:7:in `each'
    from bin/tiger_import:7

It appears there was a typo in lib/geocoder/us/import.rb.  I changed the following line:

  if Dir[File.join(root, !tables.values[0])].empty?

to

  if !Dir[File.join(root, tables.values[0])].empty?

This seems to fix the problem for me.  Hopefully this can be updated.

J

**Comment by issackelly** [comment]
Yeah, I was going to submit a patch for this, I got the same thing.

**Comment by wonderchook** [comment]
Should be fixed in the master branch now.
